---
- hosts: provisions
  become: yes
  tasks:
  - name: Add a new user named ansible
    ansible.builtin.user:
      name: ansible
      shell: /bin/bash
      groups: sudo
      password: $6$/kouQc29ofp$OskonHoWsBJ7Q1IMw5ZMi/TAu4S.8e5sWo45k7/LHXiDKG2wswcxFAM5jT1CYHaYjFJcV.qdLWEfnXrKhc3Uw0
  - name: Install public keys
    ansible.posix.authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

<<<<<<< HEAD:provision/create_ansible_user.yaml
  - name: Add devops user to the sudoers
    copy:
      dest: /etc/sudoers.d/ansible
      content: 'ansible ALL=(ALL) NOPASSWD: ALL'
<<<<<<< HEAD:provision/create_ansible_user.yaml
=======
=======
  - name: Add ansible to the sudoers
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s
>>>>>>> 1188d72123276542e7d3436c2bb77e73dff09ca9:create_ansible_user.yaml
>>>>>>> f7c31ba3d6c433c173df10361885544a66a8b91d:create_ansible_user.yaml
