---
- hosts: test 
  become: yes
  tasks:
    - name: get update
      ansible.builtin.apt:
        update_cache: yes
    
    - name: install update to the latest
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - smartmontools
        - vim
        - htop
        - curl
